# Melbourne Weather Code Workflow

## Data Cleaning

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
melb = pd.read_csv("Melbourne01.csv",low_memory=False,on_bad_lines="skip")

In [3]:
melb.columns

Index(['2011', ' 1', ' 1.1', ' 0', ' 4', ' 24.8', ' 0.0', ' 14.0', ' 51',
       ' SE', ' 11', ' 13', ' 1007.4', ' 0.0.1'],
      dtype='object')

In [4]:
melb.columns = ['Year', 'Month', 'Day', 'Hour', 'Min', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)']

In [5]:
melb.drop_duplicates().reset_index(drop=True)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
3,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
4,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575950,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
575951,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
575952,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
575953,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
575954,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [15]:
melb_str = melb[melb["Month"].map(type) == str]

In [18]:
melb_str["Month"].unique()

array([' 1', ' 2', ' 3', ' 4', ' 5', ' 6', ' 7', ' 8', ' 9', ' 10', ' 11',
       ' 12', ' 1\t18\t11\t00\t18.8\t15.9\t9.6\t55\tS\t32\t43\t1014.8\t0',
       ' 1\t18\t11\t30\t20\t16.8\t10.1\t53\tS\t28\t43\t1015.1\t0',
       ' 1\t18\t12\t00\t19\t14.8\t11.1\t60\tS\t32\t43\t1015.4\t0',
       ' 1\t18\t12\t30\t19.2\t14.9\t9.4\t53\tSSE\t35\t48\t1015.6\t0',
       ' 1\t18\t13\t00\t19.4\t15.9\t8.7\t50\tS\t30\t44\t1015.9\t0',
       ' 1\t18\t13\t30\t19.5\t15.9\t8.5\t49\tS\t33\t50\t1016.2\t0',
       ' 1\t18\t14\t00\t19.3\t15.3\t8.3\t49\tSSE\t33\t46\t1016\t0',
       ' 1\t18\t14\t30\t19.3\t15.8\t8.9\t51\tS\t33\t50\t1015.9\t0',
       ' 1\t18\t15\t00\t19.4\t15.3\t8.7\t50\tS\t35\t48\t1015.6\t0',
       ' 1\t18\t15\t30\t19.2\t14.7\t7\t45\tS\t32\t46\t1015.6\t0',
       ' 1\t18\t16\t00\t19.3\t15.8\t7.1\t45\tS\t35\t50\t1015.8\t0',
       ' 1\t18\t16\t30\t19.5\t16.3\t10\t54\tS\t32\t48\t1015.8\t0',
       ' 1\t18\t17\t00\t19\t15\t8.9\t52\tSSE\t33\t41\t1015.8\t0',
       ' 1\t18\t17\t30\t18.6\t14.6\t8.3\t51\tS\t32\t44\t1015.7\t0',
       ' 1\t18\t18\t00\t19\t15.9\t8.9\t52\tSSE\t35\t46\t1015.7\t0',
       ' 1\t18\t18\t30\t18.5\t14.6\t9.3\t55\tS\t30\t41\t1015.9\t0', ' 06',
       ' 03', ' 04', ' 05', ' 07', ' 08', ' 09', ' 01', ' 02'],
      dtype=object)

In [19]:
tabbed_months = melb_str["Month"].unique()[12:28]

In [20]:
n_position = 580364
for month in tabbed_months:
    month = month.split("\t")
    empty_first = [""] + month
    row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
    melb.loc[n_position] = row
    melb.iloc[n_position,0] = 2017
    n_position +=1

C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '11' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '15.9' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9.6' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '55' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '43' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1014.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\851566464.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(empty_first), errors = 'ignore').to_list()

In [21]:
fix_year = melb[melb['Month'].isna()].loc[::,"Year"]
indices = melb[melb['Month'].isna()].index.to_list()

In [22]:
y_position = 0
for year in fix_year:
    year = year.strip()
    year = year.split("\t")
    row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
    y_ind = indices[y_position]
    melb.loc[y_ind] = row
    y_position +=1

C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()
C:\Users\madis\AppData\Local\Temp\ipykernel_12264\2850771983.py:5: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()

In [23]:
melb[melb['Month'].isna()]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Min, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm)]
Index: []

In [24]:
melb["Day"] = melb["Day"].astype(int)

In [25]:
replace_month = {' 1': 1,
                 ' 2': 2,
                 ' 3': 3,
                 ' 4': 4,
                 ' 5': 5,
                 ' 6': 6,
                 ' 7': 7,
                 ' 8': 8,
                 ' 9': 9,
                 ' 10': 10,
                 ' 11': 11,
                 ' 12': 12,
                 ' 06': 6,
                 ' 03': 3,
                 ' 04': 4,
                 ' 05': 5,
                 ' 07': 7,
                 ' 08': 8,
                 ' 09': 9,
                 ' 01': 1,
                 ' 02': 2,
                 '09': 9,
                 '05': 5,
                 '02': 2,
                 '08': 8,
                 '1': 1,
                 '6': 6,
                 '8': 8,
                 '7': 7,
                 '5': 5,
                 '11':11
                }

In [26]:
melb["Month"] = melb["Month"].replace(replace_month)

C:\Users\madis\AppData\Local\Temp\ipykernel_12264\984582946.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  melb["Month"] = melb["Month"].replace(replace_month)

In [27]:
replace_hour = {'06': 6,
                 '03': 3,
                 '04': 4,
                 '05': 5,
                 '07': 7,
                 '08': 8,
                 '09': 9,
                 '01': 1,
                 '02': 2,
                '00': 0
                }

In [28]:
melb["Hour"] = melb["Hour"].replace(replace_hour)
melb["Hour"] = melb["Hour"].astype(int)

In [29]:
melb['Min'] = melb['Min'].astype(int)

In [30]:
melb["Air Temp (degrees C)"] = melb["Air Temp (degrees C)"].astype(float)

In [31]:
melb["Apparent Temp (degrees C)"] = melb["Apparent Temp (degrees C)"].astype(float)

In [32]:
melb["Dew Pt Temp (degrees C)"] = melb["Dew Pt Temp (degrees C)"].astype(float)

In [33]:
melb['Humidity (%)'] = melb['Humidity (%)'].astype(int)