# Melbourne Weather Code Workflow

## Data Cleaning

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
melb = pd.read_csv("Melbourne01.csv",low_memory=False,on_bad_lines="skip")

In [3]:
melb.columns

Index(['2011', ' 1', ' 1.1', ' 0', ' 4', ' 24.8', ' 0.0', ' 14.0', ' 51',
       ' SE', ' 11', ' 13', ' 1007.4', ' 0.0.1'],
      dtype='object')

In [4]:
melb.columns = ['Year', 'Month', 'Day', 'Hour', 'Min', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)']

In [5]:
melb.drop_duplicates().reset_index(drop=True)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
3,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
4,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575950,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
575951,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
575952,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
575953,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
575954,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [6]:
melb_str = melb[melb["Month"].map(type) == str]

In [9]:
tabbed_months = melb_str["Month"].unique()[12:28]

In [10]:
n_position = 580364
for month in tabbed_months:
    month = month.split("\t")
    empty_first = [""] + month
    row = pd.Series(empty_first)
    try:
        row = pd.to_numeric(row)
    except ValueError:
        pass
    row= row.to_list()
    melb.loc[n_position] = row
    melb.iloc[n_position,0] = 2017
    n_position +=1

C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '11' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '15.9' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9.6' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '55' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '43' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_65280\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1014.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row

In [11]:
fix_year = melb[melb['Month'].isna()].loc[::,"Year"]
indices = melb[melb['Month'].isna()].index.to_list()

In [12]:
y_position = 0
for year in fix_year:
    year = year.strip()
    year = year.split("\t")
    # row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()

    row = pd.Series(year)
    try:
        row = pd.to_numeric(row)
    except ValueError:
        pass
    row=row.to_list()
    
    y_ind = indices[y_position]
    melb.loc[y_ind] = row
    y_position +=1

In [13]:
melb[melb['Month'].isna()]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Min, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm)]
Index: []

In [14]:
melb["Day"] = melb["Day"].astype(int)

In [15]:
melb["Year"] = melb["Year"].astype(int)

In [16]:
replace_month = {' 1': 1,
                 ' 2': 2,
                 ' 3': 3,
                 ' 4': 4,
                 ' 5': 5,
                 ' 6': 6,
                 ' 7': 7,
                 ' 8': 8,
                 ' 9': 9,
                 ' 10': 10,
                 ' 11': 11,
                 ' 12': 12,
                 ' 06': 6,
                 ' 03': 3,
                 ' 04': 4,
                 ' 05': 5,
                 ' 07': 7,
                 ' 08': 8,
                 ' 09': 9,
                 ' 01': 1,
                 ' 02': 2,
                 '09': 9,
                 '05': 5,
                 '02': 2,
                 '08': 8,
                 '1': 1,
                 '6': 6,
                 '8': 8,
                 '7': 7,
                 '5': 5,
                 '11':11
                }

In [17]:
melb["Month"] = melb["Month"].replace(replace_month)

C:\Users\madis\AppData\Local\Temp\ipykernel_65280\984582946.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  melb["Month"] = melb["Month"].replace(replace_month)

In [18]:
replace_hour = {'06': 6,
                 '03': 3,
                 '04': 4,
                 '05': 5,
                 '07': 7,
                 '08': 8,
                 '09': 9,
                 '01': 1,
                 '02': 2,
                '00': 0
                }

In [19]:
melb["Hour"] = melb["Hour"].replace(replace_hour)
melb["Hour"] = melb["Hour"].astype(int)

In [20]:
melb['Min'] = melb['Min'].astype(int)

In [21]:
melb["Air Temp (degrees C)"] = melb["Air Temp (degrees C)"].astype(float)

In [22]:
melb["Apparent Temp (degrees C)"] = melb["Apparent Temp (degrees C)"].astype(float)

In [23]:
melb["Dew Pt Temp (degrees C)"] = melb["Dew Pt Temp (degrees C)"].astype(float)

In [24]:
melb['Humidity (%)'] = melb['Humidity (%)'].astype(int)

In [25]:
melb['Wind Gust  (km/h)'] = melb['Wind Gust  (km/h)'].astype(int)

In [26]:
melb['Wind Speed (km/h)'] = melb['Wind Speed (km/h)'].astype(int)

In [27]:
melb['MSLP (hPa)'] = melb['MSLP (hPa)'].astype(float)

In [28]:
melb['Rainfall since 9 am (mm)'] = melb['Rainfall since 9 am (mm)'].str.strip()
melb['Rainfall since 9 am (mm)'] = pd.to_numeric(melb['Rainfall since 9 am (mm)'], errors = 'coerce')

In [29]:
melb = melb.rename(columns={'Min': 'Minute'})

In [30]:
melb["Datetime"] = pd.to_datetime(melb[["Year","Month", "Hour", "Day", "Minute"]], errors = 'coerce')

In [31]:
with pd.option_context("display.max_rows",None):
    print(melb["Wind Direction"].value_counts())

Wind Direction
 N         276369
 S         136085
 W          87480
 WSW        81667
 SW         80151
 SSW        76062
 SSE        71341
 NNE        65602
 WNW        55938
 NNW        55817
 NW         40438
 SE         26632
 CALM       19598
 NE         15075
 ESE         8582
 E           7827
 ENE         7791
N             205
SW             75
S              62
SSW            60
W              43
WSW            39
WNW            30
NNE            27
NNW            20
CALM           17
NW             17
SSE            15
SE              8
 -              6
NE              5
ENE             5
 1016.6         4
 1015.9         3
 1016.1         2
 1015.6         2
 1014.6         2
 1019.5         2
 1017.4         2
 1017.0         2
ESE             2
E               2
 1020.4         2
 1021.0         2
 1012.0         1
 1017.8         1
 1010.8         1
 1019.8         1
 1019.9         1
 1021.2         1
 1010.3         1
 1017.2         1
 1021.7         1
 1021.9         1
 1022.3         1
 1022.7         1
 1004.5         1
 1022.0         1
 1016.0         1
 1013.1         1
 1016.7         1
 1026.0         1
 1019.0         1
 1008.2         1
 1003.3         1
 1029.6         1
 1024.2         1
 1025.3         1
 1026.1         1
 1016.9         1
 1015.8         1
 1014.2         1
 1016.2         1
 1014.1         1
 1014.0         1
 1013.6         1
 1012.7         1
 1014.4         1
 1015.5         1
Name: count, dtype: int64

In [32]:
melb["Wind Direction"].unique()

array([' SE', ' ESE', ' NE', ' NNE', ' ENE', ' W', ' N', ' SW', ' SSE',
       ' S', ' SSW', ' WSW', ' NW', ' WNW', ' NNW', ' E', ' CALM',
       ' 1016.6', ' 1016.9', ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1',
       ' 1025.3', ' 1024.2', ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0',
       'ENE', 'NE', 'N', 'NNE', 'NNW', 'NW', 'SSW', 'SW', 'WSW', 'W',
       'WNW', ' 1015.5', 'S', 'SE', 'SSE', 'ESE', 'CALM', 'E', ' 1014.2',
       ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0', ' 1013.6',
       ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6', ' 1015.8',
       ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5', ' 1019.8',
       ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7', ' 1021.9',
       ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3', ' 1012.0',
       ' 1010.8', ' -'], dtype=object)

In [33]:
replace_direction = {' SE': 'SE',
                     ' ESE': 'ESE',
                     ' NE': 'NE',
                     ' NNE': 'NNE',
                     ' ENE': 'ENE',
                     ' W': 'W',
                     ' N': 'W',
                     ' SW': 'SW',
                     ' SSE': 'SSE',
                     ' S': 'S',
                     ' SSW': 'SSW',
                     ' WSW': 'WSW',
                     ' NW': 'NW',
                     ' WNW': 'WNW',
                     ' NNW': 'NNW',
                     ' E': 'E',
                     ' CALM': 'STILL',
                     'CALM': 'STILL',
                    ' -': "STILL"}

In [34]:
melb["Wind Direction"] = melb["Wind Direction"].replace(replace_direction)

In [35]:
melb["Wind Direction"].unique()

array(['SE', 'ESE', 'NE', 'NNE', 'ENE', 'W', 'SW', 'SSE', 'S', 'SSW',
       'WSW', 'NW', 'WNW', 'NNW', 'E', 'STILL', ' 1016.6', ' 1016.9',
       ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1', ' 1025.3', ' 1024.2',
       ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0', 'N', ' 1015.5',
       ' 1014.2', ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0',
       ' 1013.6', ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6',
       ' 1015.8', ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5',
       ' 1019.8', ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7',
       ' 1021.9', ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3',
       ' 1012.0', ' 1010.8'], dtype=object)

In [36]:
melb["Wind Direction"].unique()

array(['SE', 'ESE', 'NE', 'NNE', 'ENE', 'W', 'SW', 'SSE', 'S', 'SSW',
       'WSW', 'NW', 'WNW', 'NNW', 'E', 'STILL', ' 1016.6', ' 1016.9',
       ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1', ' 1025.3', ' 1024.2',
       ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0', 'N', ' 1015.5',
       ' 1014.2', ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0',
       ' 1013.6', ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6',
       ' 1015.8', ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5',
       ' 1019.8', ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7',
       ' 1021.9', ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3',
       ' 1012.0', ' 1010.8'], dtype=object)

In [39]:
directions = melb["Wind Direction"].unique()

In [40]:
melb[melb["Wind Direction"] == ' 1016.6']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155560,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,0.0,0.0,2012-09-24 13:44:00
155561,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,0.0,0.0,2012-09-24 13:44:00
491736,2016,2,7,8,50,22.3,22.3,14.2,60,1016.6,0,0,0.0,0.0,2016-02-07 08:50:00
491738,2016,2,7,9,0,22.9,23.4,13.9,57,1016.6,0,0,0.0,0.0,2016-02-07 09:00:00

In [41]:
melb[melb["Wind Direction"] == ' 1017.0']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155563,2012,9,24,14,14,13.4,6.8,4.2,53,1017.0,0,0,0.0,0.0,2012-09-24 14:14:00
155564,2012,9,24,14,34,14.3,7.0,2.3,44,1017.0,0,0,0.0,0.0,2012-09-24 14:34:00

In [42]:
di_i = 0
for di in directions:
    
    fixed = di.strip()
    try:
        fixed = float(fixed)
    except (ValueError,TypeError):
        pass
    if isinstance(fixed,float):
        indx_list = melb.index[melb["Wind Direction"] == di].to_list()
        for i in indx_list:
            melb.loc[i,"MSLP (hPa)"] = fixed

In [43]:
melb[melb["Wind Direction"] == ' 1016.6']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155560,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,1016.6,0.0,2012-09-24 13:44:00
155561,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,1016.6,0.0,2012-09-24 13:44:00
491736,2016,2,7,8,50,22.3,22.3,14.2,60,1016.6,0,0,1016.6,0.0,2016-02-07 08:50:00
491738,2016,2,7,9,0,22.9,23.4,13.9,57,1016.6,0,0,1016.6,0.0,2016-02-07 09:00:00

In [44]:
melb[melb["Wind Direction"] == ' 1017.0']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155563,2012,9,24,14,14,13.4,6.8,4.2,53,1017.0,0,0,1017.0,0.0,2012-09-24 14:14:00
155564,2012,9,24,14,34,14.3,7.0,2.3,44,1017.0,0,0,1017.0,0.0,2012-09-24 14:34:00

In [46]:
for i in range(melb.shape[0]):
    if melb.loc[i, "Wind Speed (km/h)"] == 0 and melb.loc[i, "Wind Direction"] != "STILL":
        melb.loc[i, "Wind Direction"] = "STILL"
        
    if melb.loc[i, "Wind Direction"] == "STILL" and melb.loc[i, "Wind Speed (km/h)"] > 0.0:
        melb.loc[i, "Wind Direction"] = None
        
    if melb.loc[i, "Wind Speed (km/h)"] <0:
        melb.loc[i, "Wind Direction"] = None
        melb.loc[i, "Wind Speed (km/h)"] = None

    if melb.loc[i, "Wind Gust  (km/h)"] <0:
        melb.loc[i, "Wind Gust  (km/h)"] = None
        # melb.loc[i, "Wind Speed (km/h)"] = None

In [47]:
with pd.option_context('display.max_rows', None):
    print(melb["Wind Speed (km/h)"].value_counts())

Wind Speed (km/h)
13.0     93443
15.0     92110
11.0     90386
17.0     89537
9.0      83570
19.0     77005
20.0     61226
7.0      60520
22.0     54449
24.0     52009
26.0     50239
28.0     47251
30.0     39606
32.0     32826
0.0      31952
33.0     26615
35.0     21726
6.0      19908
37.0     17014
39.0     13219
41.0     10467
43.0      8221
44.0      6604
4.0       5885
46.0      5341
48.0      4428
2.0       3783
50.0      3630
52.0      2808
54.0      2171
56.0      1529
57.0      1120
59.0       752
61.0       540
63.0       381
65.0       281
67.0       181
69.0       137
70.0        76
72.0        58
74.0        41
76.0        34
80.0        20
78.0        15
83.0        10
82.0         6
85.0         6
87.0         3
89.0         2
100.0        2
3.0          1
1.0          1
Name: count, dtype: int64

In [48]:
# When there is a positive wind speed and wind direction is "STILL", I will change the wind direction to an "NaN"

# When there is a wind speed of 0, and a classified wind direction, I will change the wind direction to "STILL".

# done!

In [49]:
# melb[melb["Wind Direction"] == ' 1012.0'].index

melb.loc[657500, "Wind Direction"] = None
melb.loc[657481, "Wind Direction"] = None
melb.loc[657500, "Wind Speed (km/h)"] = None

melb.loc[657481, "Wind Speed (km/h)"] = None

In [50]:
with pd.option_context('display.float_format', '{:.2f}'.format):
    print(melb.describe())

            Year      Month        Day       Hour     Minute  \
count 1113151.00 1113151.00 1113151.00 1113151.00 1113151.00
mean     2016.50       6.45      15.76      11.44      26.12
min      2011.00       1.00       1.00       0.00       0.00
25%      2014.00       3.00       8.00       5.00      10.00
50%      2016.00       6.00      16.00      11.00      30.00
75%      2019.00       9.00      23.00      17.00      40.00
max      2025.00      12.00      31.00      23.00      59.00
std         3.53       3.44       8.81       6.89      17.24

       Air Temp (degrees C)  Apparent Temp (degrees C)  \
count            1113151.00                 1113151.00
mean                  15.78                      12.05
min                    0.50                   -9999.00
25%                   11.80                       7.60
50%                   15.10                      11.70
75%                   18.90                      16.50
max                   43.50                      43.30
std                    5.62                      15.17

       Dew Pt Temp (degrees C)  Humidity (%)  Wind Speed (km/h)  \
count               1113151.00    1113151.00         1113143.00
mean                      9.01         66.95              19.33
min                      -9.60          0.00               0.00
25%                       6.00         55.00              11.00
50%                       8.50         68.00              17.00
75%                      11.60         80.00              26.00
max                      36.90        100.00             100.00
std                       4.06         17.67              10.59

       Wind Gust  (km/h)  MSLP (hPa)  Rainfall since 9 am (mm)  \
count         1113140.00  1113151.00                1112596.00
mean               22.60     1016.99                      0.78
min                 0.00    -9999.00                      0.00
25%                13.00     1012.30                      0.00
50%                20.00     1017.40                      0.00
75%                30.00     1022.60                      0.20
max               109.00     1041.90                     54.60
std                12.72       61.36                      2.96

                            Datetime
count                        1113151
mean   2016-12-30 11:54:40.273780480
min              2011-01-01 00:04:00
25%              2014-02-06 13:40:00
50%              2016-10-17 13:50:00
75%              2019-10-13 06:35:00
max              2025-03-12 16:30:00
std                              NaN

In [51]:
melb.loc[melb["MSLP (hPa)"] <0, "MSLP (hPa)"] = None