# Melbourne Weather Code Workflow

## Data Cleaning

In [302]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [303]:
melb = pd.read_csv("Melbourne01.csv",low_memory=False,on_bad_lines="skip")

In [304]:
melb.columns

Index(['2011', ' 1', ' 1.1', ' 0', ' 4', ' 24.8', ' 0.0', ' 14.0', ' 51',
       ' SE', ' 11', ' 13', ' 1007.4', ' 0.0.1'],
      dtype='object')

In [305]:
melb.columns = ['Year', 'Month', 'Day', 'Hour', 'Min', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)']

In [306]:
melb.drop_duplicates().reset_index(drop=True)

,Year,Month,Day,Hour,Min,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm)
0,2011,1,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0
1,2011,1,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0
2,2011,1,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0
3,2011,1,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0
4,2011,1,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575950,2025,03,12.0,15.0,30.0,33.4,32.5,14.9,32.0,NW,20.0,35.0,1014.6,0.0
575951,2025,03,12.0,15.0,34.0,33.5,32.9,14.5,31.0,NNW,26.0,41.0,1014.6,0.0
575952,2025,03,12.0,16.0,0.0,34.4,34.2,14.8,30.0,WNW,26.0,41.0,1014.4,0.0
575953,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,WNW,26.0,41.0,1014.1,0.0
575954,2025,03,12.0,16.0,30.0,33.6,32.4,14.1,30.0,NW,28.0,35.0,1014.1,0.0

In [307]:
melb_str = melb[melb["Month"].map(type) == str]

In [308]:
melb_str["Month"].unique()

array([' 1', ' 2', ' 3', ' 4', ' 5', ' 6', ' 7', ' 8', ' 9', ' 10', ' 11',
       ' 12', ' 1\t18\t11\t00\t18.8\t15.9\t9.6\t55\tS\t32\t43\t1014.8\t0',
       ' 1\t18\t11\t30\t20\t16.8\t10.1\t53\tS\t28\t43\t1015.1\t0',
       ' 1\t18\t12\t00\t19\t14.8\t11.1\t60\tS\t32\t43\t1015.4\t0',
       ' 1\t18\t12\t30\t19.2\t14.9\t9.4\t53\tSSE\t35\t48\t1015.6\t0',
       ' 1\t18\t13\t00\t19.4\t15.9\t8.7\t50\tS\t30\t44\t1015.9\t0',
       ' 1\t18\t13\t30\t19.5\t15.9\t8.5\t49\tS\t33\t50\t1016.2\t0',
       ' 1\t18\t14\t00\t19.3\t15.3\t8.3\t49\tSSE\t33\t46\t1016\t0',
       ' 1\t18\t14\t30\t19.3\t15.8\t8.9\t51\tS\t33\t50\t1015.9\t0',
       ' 1\t18\t15\t00\t19.4\t15.3\t8.7\t50\tS\t35\t48\t1015.6\t0',
       ' 1\t18\t15\t30\t19.2\t14.7\t7\t45\tS\t32\t46\t1015.6\t0',
       ' 1\t18\t16\t00\t19.3\t15.8\t7.1\t45\tS\t35\t50\t1015.8\t0',
       ' 1\t18\t16\t30\t19.5\t16.3\t10\t54\tS\t32\t48\t1015.8\t0',
       ' 1\t18\t17\t00\t19\t15\t8.9\t52\tSSE\t33\t41\t1015.8\t0',
       ' 1\t18\t17\t30\t18.6\t14.6\t8.3\t51\tS\t32\t44\t1015.7\t0',
       ' 1\t18\t18\t00\t19\t15.9\t8.9\t52\tSSE\t35\t46\t1015.7\t0',
       ' 1\t18\t18\t30\t18.5\t14.6\t9.3\t55\tS\t30\t41\t1015.9\t0', ' 06',
       ' 03', ' 04', ' 05', ' 07', ' 08', ' 09', ' 01', ' 02'],
      dtype=object)

In [309]:
tabbed_months = melb_str["Month"].unique()[12:28]

In [310]:
n_position = 580364
for month in tabbed_months:
    month = month.split("\t")
    empty_first = [""] + month
    row = pd.Series(empty_first)
    try:
        row = pd.to_numeric(row)
    except ValueError:
        pass
    row= row.to_list()
    melb.loc[n_position] = row
    melb.iloc[n_position,0] = 2017
    n_position +=1

C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '11' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '15.9' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9.6' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '55' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '32' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '43' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row
C:\Users\madis\AppData\Local\Temp\ipykernel_69136\149201672.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1014.8' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  melb.loc[n_position] = row

In [311]:
fix_year = melb[melb['Month'].isna()].loc[::,"Year"]
indices = melb[melb['Month'].isna()].index.to_list()

In [312]:
y_position = 0
for year in fix_year:
    year = year.strip()
    year = year.split("\t")
    # row = pd.to_numeric(pd.Series(year), errors = 'ignore').to_list()

    row = pd.Series(year)
    try:
        row = pd.to_numeric(row)
    except ValueError:
        pass
    row=row.to_list()
    
    y_ind = indices[y_position]
    melb.loc[y_ind] = row
    y_position +=1

In [313]:
melb[melb['Month'].isna()]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Min, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm)]
Index: []

In [314]:
melb["Day"] = melb["Day"].astype(int)

In [315]:
replace_month = {' 1': 1,
                 ' 2': 2,
                 ' 3': 3,
                 ' 4': 4,
                 ' 5': 5,
                 ' 6': 6,
                 ' 7': 7,
                 ' 8': 8,
                 ' 9': 9,
                 ' 10': 10,
                 ' 11': 11,
                 ' 12': 12,
                 ' 06': 6,
                 ' 03': 3,
                 ' 04': 4,
                 ' 05': 5,
                 ' 07': 7,
                 ' 08': 8,
                 ' 09': 9,
                 ' 01': 1,
                 ' 02': 2,
                 '09': 9,
                 '05': 5,
                 '02': 2,
                 '08': 8,
                 '1': 1,
                 '6': 6,
                 '8': 8,
                 '7': 7,
                 '5': 5,
                 '11':11
                }

In [316]:
melb["Month"] = melb["Month"].replace(replace_month)

C:\Users\madis\AppData\Local\Temp\ipykernel_69136\984582946.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  melb["Month"] = melb["Month"].replace(replace_month)

In [317]:
replace_hour = {'06': 6,
                 '03': 3,
                 '04': 4,
                 '05': 5,
                 '07': 7,
                 '08': 8,
                 '09': 9,
                 '01': 1,
                 '02': 2,
                '00': 0
                }

In [318]:
melb["Hour"] = melb["Hour"].replace(replace_hour)
melb["Hour"] = melb["Hour"].astype(int)

In [319]:
melb['Min'] = melb['Min'].astype(int)

In [320]:
melb["Air Temp (degrees C)"] = melb["Air Temp (degrees C)"].astype(float)

In [321]:
melb["Apparent Temp (degrees C)"] = melb["Apparent Temp (degrees C)"].astype(float)

In [322]:
melb["Dew Pt Temp (degrees C)"] = melb["Dew Pt Temp (degrees C)"].astype(float)

In [323]:
melb['Humidity (%)'] = melb['Humidity (%)'].astype(int)

In [324]:
melb['Wind Gust  (km/h)'] = melb['Wind Gust  (km/h)'].astype(int)

In [325]:
melb['Wind Speed (km/h)'] = melb['Wind Speed (km/h)'].astype(int)

In [326]:
melb['MSLP (hPa)'] = melb['MSLP (hPa)'].astype(float)

In [327]:
melb['Rainfall since 9 am (mm)'] = melb['Rainfall since 9 am (mm)'].str.strip()
melb['Rainfall since 9 am (mm)'] = pd.to_numeric(melb['Rainfall since 9 am (mm)'], errors = 'coerce')

In [328]:
melb = melb.rename(columns={'Min': 'Minute'})

In [329]:
melb["Datetime"] = pd.to_datetime(melb[["Year","Month", "Hour", "Day", "Minute"]], errors = 'coerce')

In [330]:
melb

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0,2011-01-01 00:04:00
1,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0,2011-01-01 00:14:00
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0,2011-01-01 00:14:00
3,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11,13,1007.5,0.0,2011-01-01 00:24:00
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11,13,1007.5,0.0,2011-01-01 00:24:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113146,2025,3,12,15,30,33.4,32.5,14.9,32,NW,20,35,1014.6,0.0,2025-03-12 15:30:00
1113147,2025,3,12,15,34,33.5,32.9,14.5,31,NNW,26,41,1014.6,0.0,2025-03-12 15:34:00
1113148,2025,3,12,16,0,34.4,34.2,14.8,30,WNW,26,41,1014.4,0.0,2025-03-12 16:00:00
1113149,2025,3,12,16,30,33.6,32.4,14.1,30,WNW,26,41,1014.1,0.0,2025-03-12 16:30:00
1113150,2025,3,12,16,30,33.6,32.4,14.1,30,NW,28,35,1014.1,0.0,2025-03-12 16:30:00

In [331]:
with pd.option_context("display.max_rows",None):
    print(melb["Wind Direction"].value_counts())

Wind Direction
 N         276369
 S         136085
 W          87480
 WSW        81667
 SW         80151
 SSW        76062
 SSE        71341
 NNE        65602
 WNW        55938
 NNW        55817
 NW         40438
 SE         26632
 CALM       19598
 NE         15075
 ESE         8582
 E           7827
 ENE         7791
N             205
SW             75
S              62
SSW            60
W              43
WSW            39
WNW            30
NNE            27
NNW            20
CALM           17
NW             17
SSE            15
SE              8
 -              6
NE              5
ENE             5
 1016.6         4
 1015.9         3
 1016.1         2
 1015.6         2
 1014.6         2
 1019.5         2
 1017.4         2
 1017.0         2
ESE             2
E               2
 1020.4         2
 1021.0         2
 1012.0         1
 1017.8         1
 1010.8         1
 1019.8         1
 1019.9         1
 1021.2         1
 1010.3         1
 1017.2         1
 1021.7         1
 1021.9         1
 1022.3         1
 1022.7         1
 1004.5         1
 1022.0         1
 1016.0         1
 1013.1         1
 1016.7         1
 1026.0         1
 1019.0         1
 1008.2         1
 1003.3         1
 1029.6         1
 1024.2         1
 1025.3         1
 1026.1         1
 1016.9         1
 1015.8         1
 1014.2         1
 1016.2         1
 1014.1         1
 1014.0         1
 1013.6         1
 1012.7         1
 1014.4         1
 1015.5         1
Name: count, dtype: int64

In [332]:
melb["Wind Direction"].unique()

array([' SE', ' ESE', ' NE', ' NNE', ' ENE', ' W', ' N', ' SW', ' SSE',
       ' S', ' SSW', ' WSW', ' NW', ' WNW', ' NNW', ' E', ' CALM',
       ' 1016.6', ' 1016.9', ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1',
       ' 1025.3', ' 1024.2', ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0',
       'ENE', 'NE', 'N', 'NNE', 'NNW', 'NW', 'SSW', 'SW', 'WSW', 'W',
       'WNW', ' 1015.5', 'S', 'SE', 'SSE', 'ESE', 'CALM', 'E', ' 1014.2',
       ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0', ' 1013.6',
       ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6', ' 1015.8',
       ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5', ' 1019.8',
       ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7', ' 1021.9',
       ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3', ' 1012.0',
       ' 1010.8', ' -'], dtype=object)

In [333]:
replace_direction = {' SE': 'SE',
                     ' ESE': 'ESE',
                     ' NE': 'NE',
                     ' NNE': 'NNE',
                     ' ENE': 'ENE',
                     ' W': 'W',
                     ' N': 'W',
                     ' SW': 'SW',
                     ' SSE': 'SSE',
                     ' S': 'S',
                     ' SSW': 'SSW',
                     ' WSW': 'WSW',
                     ' NW': 'NW',
                     ' WNW': 'WNW',
                     ' NNW': 'NNW',
                     ' E': 'E',
                     ' CALM': 'STILL',
                     'CALM': 'STILL',
                    ' -': "STILL"}

In [334]:
melb["Wind Direction"] = melb["Wind Direction"].replace(replace_direction)

In [335]:
melb["Wind Direction"].unique()

array(['SE', 'ESE', 'NE', 'NNE', 'ENE', 'W', 'SW', 'SSE', 'S', 'SSW',
       'WSW', 'NW', 'WNW', 'NNW', 'E', 'STILL', ' 1016.6', ' 1016.9',
       ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1', ' 1025.3', ' 1024.2',
       ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0', 'N', ' 1015.5',
       ' 1014.2', ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0',
       ' 1013.6', ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6',
       ' 1015.8', ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5',
       ' 1019.8', ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7',
       ' 1021.9', ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3',
       ' 1012.0', ' 1010.8'], dtype=object)

In [336]:
melb["Wind Direction"].unique()

array(['SE', 'ESE', 'NE', 'NNE', 'ENE', 'W', 'SW', 'SSE', 'S', 'SSW',
       'WSW', 'NW', 'WNW', 'NNW', 'E', 'STILL', ' 1016.6', ' 1016.9',
       ' 1017.0', ' 1017.4', ' 1026.0', ' 1026.1', ' 1025.3', ' 1024.2',
       ' 1029.6', ' 1003.3', ' 1008.2', ' 1019.0', 'N', ' 1015.5',
       ' 1014.2', ' 1015.9', ' 1016.2', ' 1016.1', ' 1014.1', ' 1014.0',
       ' 1013.6', ' 1012.7', ' 1013.1', ' 1014.4', ' 1014.6', ' 1015.6',
       ' 1015.8', ' 1016.7', ' 1017.2', ' 1016.0', ' 1017.8', ' 1019.5',
       ' 1019.8', ' 1019.9', ' 1020.4', ' 1021.0', ' 1021.2', ' 1021.7',
       ' 1021.9', ' 1022.3', ' 1022.7', ' 1004.5', ' 1022.0', ' 1010.3',
       ' 1012.0', ' 1010.8'], dtype=object)

In [337]:
# pd.set_option('display.max_rows', 20)

In [338]:
directions = melb["Wind Direction"].unique()

In [339]:
melb[melb["Wind Direction"] == ' 1016.6']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155560,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,0.0,0.0,2012-09-24 13:44:00
155561,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,0.0,0.0,2012-09-24 13:44:00
491736,2016,2,7,8,50,22.3,22.3,14.2,60,1016.6,0,0,0.0,0.0,2016-02-07 08:50:00
491738,2016,2,7,9,0,22.9,23.4,13.9,57,1016.6,0,0,0.0,0.0,2016-02-07 09:00:00

In [340]:
melb[melb["Wind Direction"] == ' 1017.0']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155563,2012,9,24,14,14,13.4,6.8,4.2,53,1017.0,0,0,0.0,0.0,2012-09-24 14:14:00
155564,2012,9,24,14,34,14.3,7.0,2.3,44,1017.0,0,0,0.0,0.0,2012-09-24 14:34:00

In [341]:
di_i = 0
for di in directions:
    
    fixed = di.strip()
    try:
        fixed = float(fixed)
    except (ValueError,TypeError):
        pass
    if isinstance(fixed,float):
        indx_list = melb.index[melb["Wind Direction"] == di].to_list()
        for i in indx_list:
            melb.loc[i,"MSLP (hPa)"] = fixed

In [342]:
melb[melb["Wind Direction"] == ' 1016.6']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155560,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,1016.6,0.0,2012-09-24 13:44:00
155561,2012,9,24,13,44,14.8,6.8,0.5,37,1016.6,0,0,1016.6,0.0,2012-09-24 13:44:00
491736,2016,2,7,8,50,22.3,22.3,14.2,60,1016.6,0,0,1016.6,0.0,2016-02-07 08:50:00
491738,2016,2,7,9,0,22.9,23.4,13.9,57,1016.6,0,0,1016.6,0.0,2016-02-07 09:00:00

In [343]:
melb[melb["Wind Direction"] == ' 1017.0']

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
155563,2012,9,24,14,14,13.4,6.8,4.2,53,1017.0,0,0,1017.0,0.0,2012-09-24 14:14:00
155564,2012,9,24,14,34,14.3,7.0,2.3,44,1017.0,0,0,1017.0,0.0,2012-09-24 14:34:00

In [344]:
melb.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Air Temp (degrees C)',
       'Apparent Temp (degrees C)', 'Dew Pt Temp (degrees C)', 'Humidity (%)',
       'Wind Direction', 'Wind Speed (km/h)', 'Wind Gust  (km/h)',
       'MSLP (hPa)', 'Rainfall since 9 am (mm)', 'Datetime'],
      dtype='object')

In [345]:
for i in range(melb.shape[0]):
    if melb.loc[i, "Wind Speed (km/h)"] == 0 and melb.loc[i, "Wind Direction"] != "STILL":
        melb.loc[i, "Wind Direction"] = "STILL"
        
    if melb.loc[i, "Wind Direction"] == "STILL" and melb.loc[i, "Wind Speed (km/h)"] > 0.0:
        melb.loc[i, "Wind Direction"] = None
        
    if melb.loc[i, "Wind Speed (km/h)"] <0:
        melb.loc[i, "Wind Direction"] = None
        melb.loc[i, "Wind Speed (km/h)"] = None

    if melb.loc[i, "Wind Gust  (km/h)"] <0:
        melb.loc[i, "Wind Gust  (km/h)"] = None
        # melb.loc[i, "Wind Speed (km/h)"] = None

In [346]:
with pd.option_context('display.max_rows', None):
    print(melb["Wind Speed (km/h)"].value_counts())

Wind Speed (km/h)
13.0     93443
15.0     92110
11.0     90386
17.0     89537
9.0      83570
19.0     77005
20.0     61226
7.0      60520
22.0     54449
24.0     52009
26.0     50239
28.0     47251
30.0     39606
32.0     32826
0.0      31952
33.0     26615
35.0     21726
6.0      19908
37.0     17014
39.0     13219
41.0     10467
43.0      8221
44.0      6604
4.0       5885
46.0      5341
48.0      4428
2.0       3783
50.0      3630
52.0      2808
54.0      2171
56.0      1529
57.0      1120
59.0       752
61.0       540
63.0       381
65.0       281
67.0       181
69.0       137
70.0        76
72.0        58
74.0        41
76.0        34
80.0        20
78.0        15
83.0        10
82.0         6
85.0         6
87.0         3
89.0         2
100.0        2
3.0          1
1.0          1
Name: count, dtype: int64

In [347]:
# When there is a positive wind speed and wind direction is "STILL", I will change the wind direction to an "NaN"

# When there is a wind speed of 0, and a classified wind direction, I will change the wind direction to "STILL".

# done!

In [348]:
melb[melb["Wind Speed (km/h)"] <0]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm), Datetime]
Index: []

In [349]:
melb[melb["Wind Direction"] == ' 1017.0']

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm), Datetime]
Index: []

In [350]:
melb[melb["Wind Direction"] == ' 1010.3'].index

Index([657481], dtype='int64')

In [351]:
# melb[melb["Wind Direction"] == ' 1012.0'].index

melb.loc[657500, "Wind Direction"] = None
melb.loc[657481, "Wind Direction"] = None
melb.loc[657500, "Wind Speed (km/h)"] = None

melb.loc[657481, "Wind Speed (km/h)"] = None

In [352]:
melb[melb["Apparent Temp (degrees C)"] == 0]

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
1,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
3,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059055,2022,8,9,5,10,3.3,0.0,2.4,94,W,13.0,13.0,1027.0,0.0,2022-08-09 05:10:00
1059056,2022,8,9,5,10,3.3,0.0,2.4,94,W,13.0,13.0,1027.0,0.0,2022-08-09 05:10:00
1060262,2022,8,14,3,10,8.5,0.0,8.6,100,WNW,17.0,19.0,1008.9,0.0,2022-08-14 03:10:00
1060263,2022,8,14,3,10,8.5,0.0,8.6,100,WNW,17.0,19.0,1008.9,0.0,2022-08-14 03:10:00
1097144,2024,8,1,9,0,3.2,0.0,3.2,100,NNE,15.0,17.0,1035.4,0.2,2024-08-01 09:00:00

A lot of

In [353]:
melb["Wind Direction"].value_counts()

Wind Direction
W        357612
S        135475
WSW       81096
SW        79415
SSW       75415
SSE       70956
NNE       65203
WNW       55112
NNW       55106
NW        39759
STILL     31952
SE        26464
NE        14711
ESE        8437
E          7612
ENE        7596
N           205
Name: count, dtype: int64

In [354]:
melb["Wind Gust  (km/h)"].value_counts()

Wind Gust  (km/h)
15.0     79669
13.0     79551
17.0     77571
11.0     77352
19.0     75941
9.0      67899
26.0     61831
28.0     55486
20.0     51679
30.0     48184
24.0     44093
22.0     43650
32.0     42364
7.0      42108
33.0     36209
0.0      32282
35.0     31315
37.0     26917
39.0     22505
41.0     18740
48.0     11226
43.0     10934
6.0      10207
44.0      9776
50.0      9303
46.0      8878
52.0      7502
54.0      5899
56.0      4862
57.0      4041
59.0      3049
61.0      2527
63.0      1886
4.0       1441
65.0       984
67.0       888
69.0       885
70.0       779
72.0       640
74.0       502
76.0       362
2.0        350
78.0       266
80.0       174
82.0       135
83.0        79
89.0        49
87.0        33
85.0        32
91.0        27
93.0        24
96.0        16
95.0        15
98.0         8
104.0        5
102.0        4
100.0        4
109.0        2
Name: count, dtype: int64

In [355]:
melb[melb["MSLP (hPa)"] <0]

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
969173,2021,5,30,10,0,5.7,2.5,3.2,84,WNW,6.0,9.0,-9999.0,0.0,2021-05-30 10:00:00
969174,2021,5,30,10,30,8.2,5.9,4.8,79,NNE,4.0,9.0,-9999.0,0.0,2021-05-30 10:30:00
969175,2021,5,30,11,0,10.3,8.8,5.1,70,SE,4.0,9.0,-9999.0,0.0,2021-05-30 11:00:00
969176,2021,5,30,11,30,11.5,10.0,5.2,65,SE,2.0,9.0,-9999.0,0.0,2021-05-30 11:30:00
969177,2021,5,30,12,0,11.4,9.4,4.2,61,ENE,2.0,7.0,-9999.0,0.0,2021-05-30 12:00:00
969178,2021,5,30,12,30,12.4,11.1,4.1,57,ENE,6.0,11.0,-9999.0,0.0,2021-05-30 12:30:00
969179,2021,5,30,13,0,12.1,10.0,3.9,57,SE,9.0,11.0,-9999.0,0.0,2021-05-30 13:00:00
969180,2021,5,30,13,30,12.7,10.4,4.7,58,ESE,9.0,13.0,-9999.0,0.0,2021-05-30 13:30:00
969181,2021,5,30,14,0,13.0,10.4,4.2,55,SSE,7.0,11.0,-9999.0,0.0,2021-05-30 14:00:00
969182,2021,5,30,14,30,13.1,11.3,3.7,53,ESE,4.0,11.0,-9999.0,0.0,2021-05-30 14:30:00
969183,2021,5,30,15,0,14.1,11.9,3.3,48,ESE,4.0,9.0,-9999.0,0.0,2021-05-30 15:00:00
969184,2021,5,30,15,30,13.2,11.1,5.6,60,SE,2.0,9.0,-9999.0,0.0,2021-05-30 15:30:00
969185,2021,5,30,16,0,12.9,10.8,5.6,61,ESE,7.0,9.0,-9999.0,0.0,2021-05-30 16:00:00
969186,2021,5,30,16,30,12.4,10.3,5.8,64,STILL,0.0,0.0,-9999.0,0.0,2021-05-30 16:30:00
969187,2021,5,30,17,0,10.7,9.8,5.9,72,STILL,0.0,0.0,-9999.0,0.0,2021-05-30 17:00:00
969188,2021,5,30,17,30,9.1,8.1,5.8,80,STILL,0.0,0.0,-9999.0,0.0,2021-05-30 17:30:00
971338,2021,7,14,15,30,13.5,9.2,9.4,76,W,32.0,43.0,-9999.0,0.2,2021-07-14 15:30:00
973609,2021,8,31,8,0,13.3,8.3,4.5,55,W,52.0,63.0,-9999.0,0.0,2021-08-31 08:00:00
973610,2021,8,31,8,30,13.4,8.6,4.6,55,NNE,52.0,70.0,-9999.0,0.0,2021-08-31 08:30:00
973611,2021,8,31,9,0,13.5,9.0,4.1,53,NNE,46.0,65.0,-9999.0,0.0,2021-08-31 09:00:00
973612,2021,8,31,9,30,13.4,8.6,4.6,55,NNE,48.0,59.0,-9999.0,0.0,2021-08-31 09:30:00
1071752,2023,3,4,6,0,14.2,13.5,11.9,86,W,9.0,11.0,-9999.0,0.0,2023-03-04 06:00:00
1077157,2023,6,23,4,0,9.2,5.9,6.5,83,NNE,20.0,28.0,-9999.0,2.8,2023-06-23 04:00:00
1080185,2023,8,23,19,0,14.4,11.0,6.0,57,NNW,15.0,19.0,-9999.0,0.0,2023-08-23 19:00:00
1086140,2023,12,23,15,0,21.5,18.9,12.1,55,SSW,19.0,32.0,-9999.0,0.0,2023-12-23 15:00:00
1089098,2024,2,21,13,30,31.8,30.0,14.4,34,W,32.0,44.0,-9999.0,0.0,2024-02-21 13:30:00
1091339,2024,4,7,2,30,17.0,18.5,14.6,86,SSW,9.0,11.0,-9999.0,0.0,2024-04-07 02:30:00
1091747,2024,4,15,8,30,13.1,11.8,9.2,77,W,15.0,17.0,-9999.0,0.0,2024-04-15 08:30:00
1091748,2024,4,15,9,0,14.9,13.8,9.9,72,W,11.0,13.0,-9999.0,0.0,2024-04-15 09:00:00
1091749,2024,4,15,9,30,15.7,14.6,9.8,68,W,11.0,13.0,-9999.0,0.0,2024-04-15 09:30:00
1091750,2024,4,15,10,0,17.1,16.4,10.2,64,NNW,6.0,9.0,-9999.0,0.0,2024-04-15 10:00:00
1091751,2024,4,15,10,30,17.8,16.6,10.4,62,W,9.0,11.0,-9999.0,0.0,2024-04-15 10:30:00
1091752,2024,4,15,11,0,18.5,17.5,10.3,59,WNW,4.0,11.0,-9999.0,0.0,2024-04-15 11:00:00
1102214,2024,10,10,20,0,13.5,10.5,5.9,60,S,15.0,22.0,-9999.0,0.0,2024-10-10 20:00:00

In [356]:
with pd.option_context('display.float_format', '{:.2f}'.format):
    print(melb.describe())

           Month        Day       Hour     Minute  Air Temp (degrees C)  \
count 1113151.00 1113151.00 1113151.00 1113151.00            1113151.00
mean        6.45      15.76      11.44      26.12                 15.78
min         1.00       1.00       0.00       0.00                  0.50
25%         3.00       8.00       5.00      10.00                 11.80
50%         6.00      16.00      11.00      30.00                 15.10
75%         9.00      23.00      17.00      40.00                 18.90
max        12.00      31.00      23.00      59.00                 43.50
std         3.44       8.81       6.89      17.24                  5.62

       Apparent Temp (degrees C)  Dew Pt Temp (degrees C)  Humidity (%)  \
count                 1113151.00               1113151.00    1113151.00
mean                       12.05                     9.01         66.95
min                     -9999.00                    -9.60          0.00
25%                         7.60                     6.00         55.00
50%                        11.70                     8.50         68.00
75%                        16.50                    11.60         80.00
max                        43.30                    36.90        100.00
std                        15.17                     4.06         17.67

       Wind Speed (km/h)  Wind Gust  (km/h)  MSLP (hPa)  \
count         1113143.00         1113140.00  1113151.00
mean               19.33              22.60     1016.99
min                 0.00               0.00    -9999.00
25%                11.00              13.00     1012.30
50%                17.00              20.00     1017.40
75%                26.00              30.00     1022.60
max               100.00             109.00     1041.90
std                10.59              12.72       61.36

       Rainfall since 9 am (mm)                       Datetime
count                1112596.00                        1113151
mean                       0.78  2016-12-30 11:54:40.273780480
min                        0.00            2011-01-01 00:04:00
25%                        0.00            2014-02-06 13:40:00
50%                        0.00            2016-10-17 13:50:00
75%                        0.20            2019-10-13 06:35:00
max                       54.60            2025-03-12 16:30:00
std                        2.96                            NaN

In [357]:
melb.head(50)

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
1,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
3,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
5,2011,1,1,0,34,24.7,0.0,13.4,49,SE,11.0,11.0,1007.4,0.0,2011-01-01 00:34:00
6,2011,1,1,0,34,24.7,0.0,13.4,49,SE,11.0,11.0,1007.4,0.0,2011-01-01 00:34:00
7,2011,1,1,0,34,24.7,0.0,13.4,49,SE,11.0,11.0,1007.4,0.0,2011-01-01 00:34:00
8,2011,1,1,0,44,24.1,0.0,13.3,51,ESE,9.0,9.0,1007.3,0.0,2011-01-01 00:44:00
9,2011,1,1,0,54,24.3,0.0,13.3,50,NE,9.0,9.0,1007.3,0.0,2011-01-01 00:54:00
10,2011,1,1,0,54,24.3,0.0,13.3,50,NE,9.0,9.0,1007.3,0.0,2011-01-01 00:54:00
11,2011,1,1,1,4,24.1,0.0,13.3,51,NNE,7.0,7.0,1007.3,0.0,2011-01-01 01:04:00
12,2011,1,1,1,4,24.1,0.0,13.3,51,NNE,7.0,7.0,1007.3,0.0,2011-01-01 01:04:00
13,2011,1,1,1,14,23.5,0.0,13.6,53,ENE,7.0,9.0,1007.3,0.0,2011-01-01 01:14:00
14,2011,1,1,1,14,23.5,0.0,13.6,53,ENE,7.0,9.0,1007.3,0.0,2011-01-01 01:14:00
15,2011,1,1,1,24,23.3,0.0,13.5,54,ENE,9.0,9.0,1007.3,0.0,2011-01-01 01:24:00
16,2011,1,1,1,24,23.3,0.0,13.5,54,ENE,9.0,9.0,1007.3,0.0,2011-01-01 01:24:00
17,2011,1,1,1,34,23.6,0.0,13.5,53,ENE,6.0,7.0,1007.3,0.0,2011-01-01 01:34:00
18,2011,1,1,1,34,23.6,0.0,13.5,53,ENE,6.0,7.0,1007.3,0.0,2011-01-01 01:34:00
19,2011,1,1,1,34,23.6,0.0,13.5,53,ENE,6.0,7.0,1007.3,0.0,2011-01-01 01:34:00
20,2011,1,1,1,44,23.4,0.0,13.4,53,STILL,0.0,0.0,1007.2,0.0,2011-01-01 01:44:00
21,2011,1,1,2,14,23.7,0.0,13.8,53,STILL,0.0,0.0,1007.3,0.0,2011-01-01 02:14:00
22,2011,1,1,2,14,23.7,0.0,13.8,53,STILL,0.0,0.0,1007.3,0.0,2011-01-01 02:14:00
23,2011,1,1,2,24,23.6,0.0,13.1,51,STILL,0.0,0.0,1007.2,0.0,2011-01-01 02:24:00
24,2011,1,1,2,24,23.6,0.0,13.1,51,STILL,0.0,0.0,1007.2,0.0,2011-01-01 02:24:00
25,2011,1,1,2,34,23.1,0.0,13.3,54,STILL,0.0,0.0,1007.2,0.0,2011-01-01 02:34:00
26,2011,1,1,2,34,23.1,0.0,13.3,54,STILL,0.0,0.0,1007.2,0.0,2011-01-01 02:34:00
27,2011,1,1,2,34,23.1,0.0,13.3,54,STILL,0.0,0.0,1007.2,0.0,2011-01-01 02:34:00
28,2011,1,1,2,44,22.8,0.0,13.9,57,STILL,0.0,0.0,1007.3,0.0,2011-01-01 02:44:00
29,2011,1,1,2,54,22.4,0.0,13.8,58,STILL,0.0,0.0,1007.3,0.0,2011-01-01 02:54:00
30,2011,1,1,2,54,22.4,0.0,13.8,58,STILL,0.0,0.0,1007.3,0.0,2011-01-01 02:54:00
31,2011,1,1,3,14,21.5,0.0,14.9,66,STILL,0.0,0.0,1007.3,0.0,2011-01-01 03:14:00
32,2011,1,1,3,14,21.5,0.0,14.9,66,STILL,0.0,0.0,1007.3,0.0,2011-01-01 03:14:00
33,2011,1,1,3,34,20.7,0.0,14.4,67,SW,9.0,9.0,1007.7,0.0,2011-01-01 03:34:00
34,2011,1,1,3,34,20.7,0.0,14.4,67,SW,9.0,9.0,1007.7,0.0,2011-01-01 03:34:00
35,2011,1,1,3,44,20.4,0.0,14.6,69,SW,7.0,9.0,1007.7,0.0,2011-01-01 03:44:00
36,2011,1,1,3,44,20.4,0.0,14.6,69,SW,7.0,9.0,1007.7,0.0,2011-01-01 03:44:00
37,2011,1,1,4,4,19.2,0.0,14.8,75,SSE,13.0,15.0,1007.8,0.0,2011-01-01 04:04:00
38,2011,1,1,4,4,19.2,0.0,14.8,75,SSE,13.0,15.0,1007.8,0.0,2011-01-01 04:04:00
39,2011,1,1,4,14,18.8,0.0,14.7,77,SSE,13.0,13.0,1007.9,0.0,2011-01-01 04:14:00
40,2011,1,1,4,14,18.8,0.0,14.7,77,SSE,13.0,13.0,1007.9,0.0,2011-01-01 04:14:00
41,2011,1,1,4,24,18.5,0.0,14.9,79,SSE,11.0,13.0,1008.0,0.0,2011-01-01 04:24:00
42,2011,1,1,4,24,18.5,0.0,14.9,79,SSE,11.0,13.0,1008.0,0.0,2011-01-01 04:24:00
43,2011,1,1,4,44,18.2,0.0,14.6,79,SSE,15.0,15.0,1008.3,0.0,2011-01-01 04:44:00
44,2011,1,1,4,54,18.1,0.0,14.7,80,S,15.0,20.0,1008.4,0.0,2011-01-01 04:54:00
45,2011,1,1,4,54,18.1,0.0,14.7,80,S,15.0,20.0,1008.4,0.0,2011-01-01 04:54:00
46,2011,1,1,5,14,18.1,0.0,14.3,78,SSE,19.0,20.0,1008.9,0.0,2011-01-01 05:14:00
47,2011,1,1,5,14,18.1,0.0,14.3,78,SSE,19.0,20.0,1008.9,0.0,2011-01-01 05:14:00
48,2011,1,1,5,24,18.1,0.0,14.1,77,S,15.0,17.0,1009.2,0.0,2011-01-01 05:24:00
49,2011,1,1,5,24,18.1,0.0,14.1,77,S,15.0,17.0,1009.2,0.0,2011-01-01 05:24:00

In [358]:
melb.loc[melb["MSLP (hPa)"] <0, "MSLP (hPa)"] = None

In [359]:
melb[melb["MSLP (hPa)"] <0]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Air Temp (degrees C), Apparent Temp (degrees C), Dew Pt Temp (degrees C), Humidity (%), Wind Direction, Wind Speed (km/h), Wind Gust  (km/h), MSLP (hPa), Rainfall since 9 am (mm), Datetime]
Index: []

In [360]:
with pd.option_context('display.float_format', '{:.2f}'.format):
    print(melb.describe())

           Month        Day       Hour     Minute  Air Temp (degrees C)  \
count 1113151.00 1113151.00 1113151.00 1113151.00            1113151.00
mean        6.45      15.76      11.44      26.12                 15.78
min         1.00       1.00       0.00       0.00                  0.50
25%         3.00       8.00       5.00      10.00                 11.80
50%         6.00      16.00      11.00      30.00                 15.10
75%         9.00      23.00      17.00      40.00                 18.90
max        12.00      31.00      23.00      59.00                 43.50
std         3.44       8.81       6.89      17.24                  5.62

       Apparent Temp (degrees C)  Dew Pt Temp (degrees C)  Humidity (%)  \
count                 1113151.00               1113151.00    1113151.00
mean                       12.05                     9.01         66.95
min                     -9999.00                    -9.60          0.00
25%                         7.60                     6.00         55.00
50%                        11.70                     8.50         68.00
75%                        16.50                    11.60         80.00
max                        43.30                    36.90        100.00
std                        15.17                     4.06         17.67

       Wind Speed (km/h)  Wind Gust  (km/h)  MSLP (hPa)  \
count         1113143.00         1113140.00  1113117.00
mean               19.33              22.60     1017.33
min                 0.00               0.00      988.10
25%                11.00              13.00     1012.30
50%                17.00              20.00     1017.40
75%                26.00              30.00     1022.60
max               100.00             109.00     1041.90
std                10.59              12.72        7.64

       Rainfall since 9 am (mm)                       Datetime
count                1112596.00                        1113151
mean                       0.78  2016-12-30 11:54:40.273780480
min                        0.00            2011-01-01 00:04:00
25%                        0.00            2014-02-06 13:40:00
50%                        0.00            2016-10-17 13:50:00
75%                        0.20            2019-10-13 06:35:00
max                       54.60            2025-03-12 16:30:00
std                        2.96                            NaN

In [361]:
melb

,Year,Month,Day,Hour,Minute,Air Temp (degrees C),Apparent Temp (degrees C),Dew Pt Temp (degrees C),Humidity (%),Wind Direction,Wind Speed (km/h),Wind Gust (km/h),MSLP (hPa),Rainfall since 9 am (mm),Datetime
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
1,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
3,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113146,2025,3,12,15,30,33.4,32.5,14.9,32,NW,20.0,35.0,1014.6,0.0,2025-03-12 15:30:00
1113147,2025,3,12,15,34,33.5,32.9,14.5,31,NNW,26.0,41.0,1014.6,0.0,2025-03-12 15:34:00
1113148,2025,3,12,16,0,34.4,34.2,14.8,30,WNW,26.0,41.0,1014.4,0.0,2025-03-12 16:00:00
1113149,2025,3,12,16,30,33.6,32.4,14.1,30,WNW,26.0,41.0,1014.1,0.0,2025-03-12 16:30:00
1113150,2025,3,12,16,30,33.6,32.4,14.1,30,NW,28.0,35.0,1014.1,0.0,2025-03-12 16:30:00